# Generated by Django 3.0 on 2019-12-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='This picture will be uploaded to AWS.', null=True, upload_to='episodes/'),
        ),
    ]
