# Generated by Django 3.0 on 2019-12-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_auto_20191218_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='content',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='overview',
        ),
    ]
