# Generated by Django 2.2 on 2020-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_episode_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='background',
            field=models.ImageField(blank=True, help_text='This picture will be uploaded to AWS.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='This picture will be uploaded to AWS.', null=True, upload_to=''),
        ),
    ]
