# Generated by Django 2.2 on 2020-03-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0006_auto_20200328_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=199, unique=True),
        ),
    ]
