# Generated by Django 2.2 on 2020-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0007_auto_20200328_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='content',
            field=models.TextField(blank=True, help_text='Actual text content for a Podcast, transcriptions etc.', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for list of Episodes.', null=True),
        ),
    ]
