# Generated by Django 2.2 on 2020-05-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0008_auto_20200329_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-publish',), 'verbose_name': 'Podcaster', 'verbose_name_plural': 'Podcaster'},
        ),
    ]
