# Generated by Django 2.2 on 2020-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en_US',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_ES',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_en_US',
            field=models.CharField(blank=True, help_text='SEO Description appearing in search engines.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_es_ES',
            field=models.CharField(blank=True, help_text='SEO Description appearing in search engines.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords_en_US',
            field=models.CharField(blank=True, help_text='SEO Keywords helping in users searches.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords_es_ES',
            field=models.CharField(blank=True, help_text='SEO Keywords helping in users searches.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_en_US',
            field=models.CharField(blank=True, help_text='SEO Title appearing in search engines.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_es_ES',
            field=models.CharField(blank=True, help_text='SEO Title appearing in search engines.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='overview_en_US',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='overview_es_ES',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en_US',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Created automatically, no need to fill.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_es_ES',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Created automatically, no need to fill.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_US',
            field=models.CharField(max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es_ES',
            field=models.CharField(max_length=199, null=True),
        ),
    ]
