# Generated by Django 3.0 on 2019-12-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_pagebackground_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('select', 'SELECT'), ('title', 'TITLE')], default='select', max_length=25, unique=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
