# Generated by Django 3.0 on 2019-12-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_pagedescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedescription',
            options={'verbose_name': 'Page Description', 'verbose_name_plural': 'Page Description'},
        ),
    ]
