# Generated by Django 2.2 on 2020-03-29 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_description', models.TextField(blank=True, null=True)),
                ('personal_description', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='This picture will be uploaded to AWS.', null=True, upload_to='profile_pictures/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
