# Generated by Django 2.2 on 2020-03-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='patreon_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
