# Generated by Django 2.2 on 2020-05-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200329_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='patreon_link',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='personal_description',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='podcast_description',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='publish',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='name',
            field=models.TextField(choices=[('select', 'SELECT'), ('podcast_description', 'PODCAST_DESCRIPTION'), ('profile_description', 'PROFILE_DESCRIPTION'), ('patreon', 'PATREON'), ('paypal', 'PAYPAL')], default='select', max_length=500, unique=True),
        ),
    ]
