# Generated by Django 2.2 on 2020-05-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200501_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='name',
            field=models.CharField(choices=[('select', 'SELECT'), ('podcast_description', 'PODCAST_DESCRIPTION'), ('profile_description', 'PROFILE_DESCRIPTION'), ('patreon', 'PATREON'), ('paypal', 'PAYPAL')], default='select', max_length=500, unique=True),
        ),
    ]
